#!/bin/bash

# Run fastqc
# 48 RNASeq fastq file=walltime=00:10:00,ncpus=48,mem=192GB,wd
# Multiply walltime or number of CPUs according to fastq number/size
# fastQC efficiency ~0.9 - 1

#PBS -P er01
#PBS -N fastqc
#PBS -l walltime=00:30:00,ncpus=48,mem=192GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01+scratch/hm82
#PBS -o ./Logs/fastqc.o
#PBS -e ./Logs/fastqc.e

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load fastqc/0.11.7

set -e

# M = Number of tasks per node
# NCPUs = CPUs per task
M=48
NCPUS=1

SCRIPT=./fastqc.sh
INPUTS=./Inputs/fastqc.inputs

echo "$(date): FastQC."

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
	--map-by node:PE=${NCPUS} \
	nci-parallel \
	--verbose \
	--input-file ${PBS_JOBFS}/input-file
