#!/bin/bash
#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs fastqc.sh in parallel.
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_pon_gathervcfs_run_parallel.pbs
# Job resource requirements:
#       48 RNASeq fastq file=walltime=00:10:00,ncpus=48,mem=192GB,wd
#       Multiply walltime or number of CPUs according to fastq number/size
#       fastQC efficiency ~0.9 - 1
# Per task requirements:
#       1 task (1 FASTQ file) requires 1 CPU, 4GB mem
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 18/03/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N fastqc
#PBS -l walltime=00:30:00,ncpus=28,mem=128GB,wd
#PBS -q normalbw
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ../Logs/fastqc.o
#PBS -e ../Logs/fastqc.e

set -e

# Software
module load fastqc/0.11.7

# SCRIPT
INPUTS=./Inputs/fastqc.inputs

#########################################################
# Do not edit below this line
#########################################################

module load openmpi/4.0.2
module load nci-parallel/1.0.0

# NCPUs = CPUs per task
NCPUS=1

# SCRIPT
SCRIPT=./fastqc.sh

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
